Integration
WildCodeSchool/2109-wns-paris-les-semicroustillant-front pull request #10
Opened 2022-01-20 15:42 UTC by dev-talbi

2022-01-20 16:36 UTC, FredyLy requested changes

2022-01-20 16:36 UTC, FredyLy commented on src/components/Navbar.tsx
> +// @ts-nocheck
```
/* eslint-disable */
 // @ts-nocheck
```

To be deleted :)

2022-01-20 16:36 UTC, FredyLy commented on src/components/Navbar.tsx
> +                        Géstion des utilisateurs
Accent on `Gestion` word to be deleted

2022-01-20 16:45 UTC, dev-talbi commented on src/components/Navbar.tsx
> +                        Géstion des utilisateurs
c'est fait

2022-01-20 16:45 UTC, dev-talbi commented on src/components/Navbar.tsx
> +// @ts-nocheck
c'est fait

2022-01-20 16:47 UTC, FredyLy approved these changes

2022-01-21 08:51 UTC, SophieTopart approved these changes
OK

2022-01-21 08:51 UTC, merged