Feat/tickets
WildCodeSchool/2109-wns-paris-les-semicroustillant-front pull request #34
Opened 2022-06-30 15:08 UTC by SophieTopart

2022-06-30 15:26 UTC, grubux requested changes

2022-06-30 15:26 UTC, grubux commented on src/components/TasksList/AddTaskCard.tsx
> +  const statuses = ['In progress', 'To do', 'Done'];
Se dit "statutes"

2022-06-30 15:26 UTC, grubux commented on src/components/TasksList/AddTaskCard.tsx
> +  const [createdByInputValue, setCreatedByInputValue] = React.useState('');
import {useState} from React et tu utilises useState('')

2022-06-30 15:26 UTC, grubux commented on src/components/TasksList/AddTaskCard.tsx
> +    project_id: '',
il me semble qu'on utilise le camelCase pour un objet JSON ?

2022-06-30 15:26 UTC, grubux commented on src/components/TasksList/AddTaskCard.tsx
> +    created_by: false,
camelCase ?

2022-06-30 15:26 UTC, grubux commented on src/components/TasksList/AddTaskCard.tsx
> +                  // eslint-disable-next-line react/jsx-props-no-spreading
Il n'y a pas moyen de passer les props nécéssaires en clair ?

2022-06-30 15:26 UTC, grubux commented on src/components/TasksList/TaskCard.tsx
> +        sx={{ marginTop: 5, marginBottom: 5, minWidth: 275, maxWidth: 300 }}
Utilisons le styled component de Mui ?

2022-06-30 15:26 UTC, grubux commented on src/components/TasksList/TaskList.tsx
> +      <div>
Mui ?

2022-06-30 15:26 UTC, grubux commented on src/components/TasksList/UpdateTaskCard.tsx
> +export default UpdateTaskCard;
Le fichier semble long

2022-06-30 15:26 UTC, grubux commented on src/styles/TaskList.css
> +  justify-content: space-between;
styled Component de Mui

2022-06-30 18:44 UTC, SophieTopart commented on src/components/TasksList/AddTaskCard.tsx
> +  const statuses = ['In progress', 'To do', 'Done'];
Souhaites-tu vraiment me donner à moi des leçons d'anglais ?
https://www.merriam-webster.com/dictionary/status

2022-06-30 18:45 UTC, SophieTopart commented on src/components/TasksList/AddTaskCard.tsx
> +    project_id: '',
J'ai repris ici les noms des variables déterminées dans le back

2022-06-30 18:46 UTC, SophieTopart commented on src/components/TasksList/AddTaskCard.tsx
> +                  // eslint-disable-next-line react/jsx-props-no-spreading
Ça peut se faire uniquement si je fais la même opération dans le composant parent, l'info n'y est pas disponible.

2022-06-30 18:47 UTC, SophieTopart commented on src/components/TasksList/TaskCard.tsx
> +        sx={{ marginTop: 5, marginBottom: 5, minWidth: 275, maxWidth: 300 }}
Le style en ligne est aussi possible, va-t-on réutiliser cette carte ailleurs ?

2022-07-01 08:04 UTC, grubux commented on src/components/TasksList/AddTaskCard.tsx
> +  const statuses = ['In progress', 'To do', 'Done'];
--' j'ai fait une traduction Deepl car je n'étais pas sûr, my bad...

2022-07-01 08:04 UTC, grubux commented on src/components/TasksList/AddTaskCard.tsx
> +  const statuses = ['In progress', 'To do', 'Done'];
--' j'ai fait une traduction Deepl car je n'étais pas sûr, my bad...

2022-07-01 08:14 UTC, grubux approved these changes

2022-07-01 08:15 UTC, merged